# Jekyll workshop-template https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

title: go-go gh-pages!
description: > 
  Learn about GitHub pages and Jekyll. 
keywords: "github, github-pages, websites, static gen, hosting, html, workshop, gh-pages"

url: "https://evanwill.github.io/go-go-ghpages" 

# author settings for cc-by
author: evan will
github_username: evanwill
pub_year: 2017
repo: "https://github.com/evanwill/go-go-ghpages"

google_analytics: UA-74844011-1

# Build settings
markdown: kramdown

# figure include: {% include image.html file="cat.jpg" alt="kitten" cap="My cat" width="45%" %}