# Jekyll workshop-template https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

title: Shannon MacKenzie
description: > 
  description goes here. 
keywords: "keywords"

url: "https://shannonmackenzie.github.io" 

# author settings for cc-by
author: Shannon MacKenzie
github_username: shannonmackenzie
pub_year: 2017
repo: "https://github.com/shannonmackenzie.github.io"

include: ["/_pages/"]

# Build settings
markdown: kramdown

# figure include: {% include image.html file="cat.jpg" alt="kitten" cap="My cat" width="45%" %}
